---
toc-title: "Chapter 9"
---

# Conclusion {#sec-conclusion}

::: {.content-visible when-format="html"}
{{< include style/macros-html.md >}}
{{< include style/macros.md >}}
:::

The main contribution of this thesis has been to solve @prob-spectroscopy-problem, the *spectroscopy problem*, deciding all behavioral preorders and equivalences of strong and weak spectrum, in one go.
For this objective, we have provided *generalized game characterizations* for both spectra.
To turn these into decision procedures, we have developed a theory of *Galois energy games*.
Thanks to the decision procedures, we can offer *tool support* for equivalence spectroscopies.
So, indeed, there is such a thing as “linear-time--branching-time spectroscopy” (@idea-spectroscopy).

{{< paragraph_heading "The big picture." >}}
@fig-conclusion-big-picture shows the steps our theory has taken:

::: {#fig-conclusion-big-picture fig-env="figure*" fig-pos="bt"}
```tikz
\begin{adjustbox}{max width=.9\linewidth}
  \begin{tikzpicture}[auto,node distance=2.5cm,
    algstep/.style={minimum width=3cm, minimum height=1.4cm, draw=gray, rectangle,align=center,rounded corners}]
    \node[algstep, draw] (WeakSpectro) {Weak spectroscopy \\ Chapter \ref{sec-weak-spectorscopy}};
    \node[algstep, draw, below of=WeakSpectro] (StrongSpectro) {Strong spectroscopy \\ Chapter \ref{sec-strong-spectroscopy}};
    \node[algstep, draw, left of=StrongSpectro, node distance=6cm, minimum width=4cm] (PolySpectro) {Polynomial spectroscopy \\ Chapter \ref{sec-approach}};
    \node[algstep, draw, below of=PolySpectro, minimum width=4cm] (BisimGame) {Bisimulation game \\ Chapter \ref{sec-preliminaries}};
    \node[algstep, draw, left of=BisimGame, node distance=6cm] (HMThm) {Hennessy–Milner\\ theorem};

    \path[->, dashed, thick]
      (HMThm) edge node[align=center, swap] {certificates of\\strategies} (BisimGame)
      (BisimGame) edge node[align=left, swap] {$(\infty, \infty, \infty)$-instance of\\ bisimulation energy game} (PolySpectro)
      (PolySpectro) edge node[align=left, swap] {3d-version} (StrongSpectro)
      (StrongSpectro) edge node[align=left, swap] {special case with\\no internal $\tau$} (WeakSpectro);


    \node[left=3mm of HMThm, align=right] (IndividualEqs) {Individual\\equivalences\\as baseline};
    \node[left=3mm of PolySpectro, align=right] (Spectra) {Spectra\\of equivalence\\ Chapter \ref{sec-spectrum}};
    \node[left=3mm of WeakSpectro, align=right] (WeakSpectra) {Abstracting\\ silent steps \\ Chapter \ref{sec-weak-spectrum}};
  \end{tikzpicture}
\end{adjustbox}
```

Hierarchy of abstraction from Hennessy--Milner theorem and strong bisimilarity to weak spectroscopy.
(Read arrows as “… can be understood as … of …”.)
:::

- We have started at the *level of individual equivalences* by revisiting the classical Hennessy–Milner theorem on the dualism of modal distinguishability and behavioral relatability for bisimilarity.
- @sec-preliminaries has revealed how relations and modal formulas in the Hennessy–Milner theorem are just *certificates* for defender and attacker strategies in the bisimulation reachability game (@idea-games).
- @sec-spectrum has taken us to the level of *spectra* of equivalence, following van Glabbeek's approach of a *hierarchy of Hennessy–Milner theorems* (@idea-modal-first, @idea-hierarchy).
- On this level, @sec-approach has discovered that the bisimulation game just is an instance of the bisimulation *energy* game, which characterizes a small spectrum of $\complexityname{P}$-easy strong equivalences (@idea-energy-games).
  We can use it in algorithms thanks to our decision procedure for such *Galois energy games* (@idea-deciding-energy-games).
- The bisimulation energy game then again is only a lower-dimensional sibling of the *strong spectroscopy game*, which characterizes the full strong spectrum in @sec-strong-spectroscopy by a subset construction (@idea-subset-construction).
  We can still project it back all the way to the bisimulation game (@idea-instance-games).
- With @sec-weak-spectrum, we have entered the level of van Glabbeek's [-@glabbeek1993ltbt] *weak spectrum*, where silent steps are abstracted,
  through a weakening of $\hml$ (@idea-weak-hml).
- @sec-weak-spectorscopy has introduced the *weak spectroscopy game*, where the defender profits from internal transitions (@idea-weakening-game).
  Where there is no internal $\step{\tau}$-activity, the game could still serve as a strong spectroscopy game. 

In much the same way as we understand equivalences in a hierarchy by folding away dimensions of distinctions, this thesis itself has followed a hierarchy of spectroscopies.
Starting from the Hennessy–Milner theorem, we have *unfolded* aspects, up to the weak spectroscopy.
If one looks closely, we have even started one level below:
@rem-leq-bisim-game notices that the subtractive $\leq$-game on natural numbers is an instance of the simulation game.

One could frame this journey along Plato's allegory of the cave:
The Hennessy–Milner theorem *is a shadow* of the bisimulation game, which is a shadow of an energy game, which is a shadow of the strong spectroscopy game, which is a shadow of the weak spectroscopy game.
With the tool implementations of @sec-implementations, we have returned from the abstract realm of ideas back to a more material level.

But in reality, there is not one single *ideal* hierarchy of abstraction.
Our journey has crossed many routes by other researches and could have taken different paths.
Many interesting ones have been the topic of “Discussion” sections at the end of chapters.
Let us close by looking at some ways one could go from here.

{{< paragraph_heading "Blank spots." >}}
There are some classical points to extend research around this thesis. For instance:

- More formalization:
  Our Isabelle/HOL theory of the weak spectroscopy strengthens many results of the thesis (thanks to the hierarchy of shadows, @fig-conclusion-big-picture).
  But so far, it does not cover revivals and thus failure-trace-like notions.
  The proofs in @bisping2023equivalenceEnergyGamesReport give some confidence that the construction is correct, but an Isabelle/HOL formalization would be even nicer.
- More Galois energy games:
  There exist some interesting questions around the theory of Galois energy games of @sec-approach and their generalizability to more game variants.^[
    Lemke and Bisping are already writing a paper on this.
  ]
- More tool support:
  Proliferation of spectroscopy features to more tools beyond @sec-implementations would be great.
  Our existing open source implementations can hopefully serve as good starting points.

{{< paragraph_heading "More spectra." >}}
Concurrency theory knows other variants of linear-time--branching-time spectra.
For some, it might be worthwhile to ask spectroscopy questions or to adapt our approach of generalized game characterizations.

- There are various *quantitative notions*, often understood in terms of *behavioral distances*.
  They could be included into our game model by allowing the defender a certain amount of “cheating.”
  For instance, the $Q$-sets in game positions could be fuzzy, and some defender-budget defines how unlikely positions they can pick.

  The (strong) quantitative spectrum of @fahrenberg2014quantitativeLTBTS already is phrased in terms of a game model.
  Combining it with our game would likely demand deeper changes to our game mechanics, because one has to remember traces (and not just current states) to compute the resulting distances in full generality.

  For Markovian models and probabilistic bisimilarities, there is recent work of “spectro-fication” in
  @ba2017bisimTraceApproximate, @bdh2020probabilisticSpectrum, and @sbkpq2024approximateProbabilisticBisimulations, also extending to silent-step notions.
  So, this might be the kind of quantitative equivalences where a connection to our approach works best.

  Timed equivalences would face conceptional boundaries to decision procedures on finite models:
  While bisimilarity is decidable, trace preordering is not [@cerans1993decidabilityTimedBisim].
- *Barbed and other congruences* on $\pi$-calculi rely on some system of *contexts* in which to place processes.
  @Fournet2005 present a hierarchy for asynchronous name-passing calculi, on which one could base a spectroscopy.
  @valmari2020allWeakCongruencesBelowFairTesting even identifies a spectrum of *all* linear-time congruences for a sensible set of operators.

  Conceptionally, it is clear that the selection of a distinguishing context could also happen as an attacker move.
  In practice, it might be hard to do this elegantly in a way where games remain finite for finite systems.
  Likely, the most feasible route leads through *conditional equivalences* [@hkks2020conditionalBisim].
- Some kinds of bisimilarity are based on *special modalities*.
  For instance, there are forward/reverse bisimilarities [@be2023forwardReverseBisim] that add modalities to move backwards through the transition graph.

  Many such modalities could be added as special moves to the game graph.
  For modalities where satisfaction depends on infinite behavior, the reachability game framework is not sufficiently expressive.
  An example would be the divergence modalities mentioned in @sec-extending-to-other-eqs, which require a parity-game winning condition.

{{< paragraph_heading "A modal-logical turn?" >}}
This thesis has approached the rich body of work on equivalence and refinement through one unified lens of *finding differences* in behavior.
These were expressed in *modal logics* (@idea-modal-first “Modal first!”), which comes with several perks.

In recent years, there seems to be a shift towards the “modal first” approach.
The shift is visible in Geuvers and Golov's work on apartness [@geuversGolov2023positiveBB; @geuvers2022],
similarly in @fms2021behavioralPreordGradedMonads and @fswbgm2024gradedSemantics connecting graded modal logics and monads,
in @wms2021explainingBehavioralInequivGenerically strongly linking partition refinement and modal logic,
as well as in @bgkm2023hmThmsViaGalois using Galois connections to obtain Hennessy–Milner theorems.

This thesis and its surrounding publications, too, participate in this movement.
However, we leave the stack of abstractions around coalgebras and monads aside.
One of the effects of this decision is that our framework can be implemented by regular Bachelor students after one introductory course on reactive systems.

{{< paragraph_heading "The encyclopedic project." >}}
Concurrency theory as a field has entered a stage where the initial explosion of questions and approaches has faded.
A wave of Festschriften has been appearing.
As @garavel2023calculiWrong puts it:

> Time has come for encyclopedic synthesis: reexamine / select / simplify / sort

This thesis hopes to fit into this project with a “search engine” for equivalences.
It shows how to quickly survey spectra of equivalence and how the approach can easily be implemented into tools.
While pioneers of the field are retiring, parts of their wisdom thus can be materialized into new generations of software.

… for concurrent computation will remain relevant, and so will questions on the equivalence of concurrent programs.
