project:
  type: book
  output-dir: _book
  execute-dir: project
  preview:
    port: 5588
    navigate: false
    watch-inputs: false
    timeout: 30

filters:
#- teximg
- noindent
- diagram

number-sections: true
crossref:
  chapters: true
  custom:
    - kind: float
      reference-prefix: Algorithm
      key: alg
      latex-env: algorithm
linestretch: 1.1
fig-align: center
strip-comments: true
syntax-definitions: 
  - style/ccs.xml
  - style/isabelle.xml


book:
  title: "Generalized Equivalence Checking of Concurrent Programs"
  author:
  - name: Benjamin Bisping
    email: benjamin.bisping@tu-berlin.de
    url: https://bbisping.de
    affiliation: MTV TU Berlin
    affiliation-url: https://www.mtv.tu-berlin.de
  date-format: long
  #abstract: "..."
  repo-url: https://github.com/benkeks/generalized-equivalence-checking
  repo-actions: [edit]
  downloads: [pdf]
  chapters:
    - index.qmd
    - 01_introduction.qmd
    - 02_background.qmd
    - 03_equivalence-spectrum.qmd
    - 04_spectrum-to-games.qmd
    - 05_strong-spectroscopy.qmd
    - 06_weak-spectrum.qmd
    - 07_silent-step-spectroscopy.qmd
    - 08_implementations.qmd
    - 09_conclusion.qmd
    - 10_references.qmd

bibliography: similarities.bib
csl: http://www.zotero.org/styles/apa
#csl: iso690-author-date-en

format:
  html:
    from: markdown
    theme: cosmo
    html-math-method: katex
    #fig-cap-location: margin
    reference-location: margin
    crossrefs-hover: true # this lead to poor preview browsing experience and katex exceptions :/
    citation-location: margin
    linestretch: 1.3
    mainfont: KaTeX_Main
    monofont: DejaVu Sans Mono
    css: style/style.css
    grid:
      sidebar-width: 300px
      body-width: 800px
      margin-width: 300px
      gutter-width: 1.5rem
    other-links:
    - text: PDF version
      icon: file-pdf
      href: ./Generalized-Equivalence-Checking-of-Concurrent-Programs.pdf
    - text: GitHub
      icon: github
      href: https://github.com/benkeks/generalized-equivalence-checking
  pdf:
    documentclass: book
    classoption: [oneside]
    pdf-engine: xelatex
    mainfont: Linux Libertine O
    monofont: DejaVu Sans Mono
    indent: true
    colorlinks: true # must be set in order for quarto to load dvipsnames in xcolor for book class ....
    papersize: a4
    top-level-division: chapter
    toc: true
    template-partials:
      - style/before-body.tex
      - style/toc.tex
    #keep-md: true
    #keep-tex: true
    geometry:
    - left=2.5cm
    - textwidth=11cm
    - marginparsep=0.5cm
    - marginparwidth=5.5cm
    reference-location: margin
    include-in-header: style/preamble.tex
    #include-before-body:
    #  text: |
    #    \renewcommand{\bibsection}{}
    #cite-method: natbib
    biblio-config: true
    link-citations: true
    latex-max-runs: 4
    mermaid:
      theme: neutral

# jupyter:
#  kernelspec:
#    display_name: Scala 3
#    language: scala
#    name: scala

diagram:
  cache: true
  cache-dir:
    _cache_diagrams
  engine:
    tikz:
      execpath: xelatex
      header-includes:
        - '\usepackage{unicode-math}'
        - '\input{PROJECT/style/preamble.tex}'
        - '\input{PROJECT/style/macros.md}'
    dot:
      execpath: dot
      format: svg
