
::: {.content-visible when-format="html"}
{{< include style/macros-html.md >}}
:::
{{< include style/macros.md >}}

:::{#summary-block-en}
We study the *spectroscopy problem* that asks which notions from a spectrum of behavioral equivalences relate a pair of states in a transition system.
This allows a generalized handling of questions on *how equivalent two programs are*.

As *main result*, we solve the spectroscopy problem for *finite-state systems* and a hierarchy of semantic models known as the *weak linear-time–branching-time spectrum*, due to van Glabbeek.
The spectrum arises because of different ways of understanding nondeterminism and internal behavior in models of concurrent programs.
We also treat the *strong spectrum* (without internal behavior) as well as use cases of generalized equivalence checking in verification and concurrency theory.

Our *approach* relies on a *quantitative understanding of spectra* in terms of how many syntactic features of Hennessy–Milner modal logic are used to characterize equivalences.

As *key trick* to solve the spectroscopy problem, we prove spectra of equivalence to be captured by *spectroscopy games* where energy budgets bound the features an attacker may use to express differences of states.
Optimal attack strategies correspond to *distinguishing formulas* with a minimal usage of syntax.
The spectroscopy problem thus reduces to the problem of computing *minimal attacker-winning budgets* in spectroscopy games.
For this, we provide an algorithm to compute such budgets on a wider class of *Galois energy games*.
The resulting spectroscopy algorithms are exponential for the $\complexityname{PSPACE}$-hard spectrum of equivalence problems, but can be instantiated to polynomial-time solutions on the $\complexityname{P}$-easy part.

Aiming for *applicability*, we implement the spectroscopy procedure in the web tool {{< equivio >}}, which continues a tradition of *concurrency workbenches*.
Using it, we can *check for dozens of equivalences* at once.
We apply the spectroscopy approach to small *case studies from verification and translation of concurrent programs*.
Core parts of the thesis are supported by an *Isabelle/HOL formalization*.
:::

:::{#summary-block-de}
Wir befassen uns mit dem *Spektroskopie-Problem*.
Dieses fragt, welche Verhaltensgleichheiten eines Spektrums Zustände in einem Transitionssystem in Beziehung setzen.
Damit wird es möglich, die Frage, *wie äquivalent zwei Programme sind*, allgemein zu handhaben.

Als *Hauptergebnis* lösen wir das Spektroskopie-Problem für Systeme mit endlichem Zustandsraum und eine Hierarchie semantischer Modelle, die als „Schwaches Linearzeit–Verzweigungszeit-Spektrum“ nach van Glabbeek bekannt ist.
Dieses Spektrum ergibt sich aus verschiedenen Wegen, Nichtdeterminismus und internes Verhalten in Modellen nebenläufiger Programme zu fassen.
Wir behandeln auch das „Starke Spektrum“ (ohne internes Verhalten) sowie diverse Anwendungsfälle generalisierter Äquivalenzprüfung in Verifikation und Nebenläufigkeitstheorie. 

Unser *Ansatz* ruht auf einem *quantitativen Verständnis von Spektren* darin, wie viele syntaktische Möglichkeiten in Hennessy–Milner-Modallogik zur Charakterisierung verwendet werden. 

Der *zentrale Trick* zur Lösung des Spektroskopie-Problems ist, zu zeigen, wie Gleichheitsspektren durch *Spektroskopie-Spiele* abgedeckt werden.
In diesen begrenzen Energiebudgets die Möglichkeiten eines Angreifers, der Unterschiede zwischen Zuständen ausdrücken möchte.
Optimale Angriffsstrategien korrespondieren zu *unterscheidenden Formeln*, die minimale syntaktische Möglichkeiten nutzen.
Das Spektroskopie-Problem reduziert sich damit auf die Berechnung *minimaler Budgets*, mit denen der Angreifer in Spektroskopie-Spielen gewinnt.
Hierzu liefern wir einen Algorithmus, mit dem sich solche Budgets für eine größere Klasse von *Galois-Energie-Spielen* ermitteln lassen.
Die sich ergebenden Spektroskopie-Algorithmen sind exponentiell für das $\complexityname{PSPACE}$-harte Spektrum von Gleichheitsproblemen, aber lassen sich zu polynomiellen Lösungen für den $\complexityname{P}$-einfachen Teil instanziieren.

Mit dem Ziel der *Anwendbarkeit* implementieren wir die Spektroskopie im Web-Tool {{< equivio >}}.
Dieses Programm folgt einer Tradition von *Concurrency-Workbenches*.
Mit ihm lassen sich *dutzende Gleichheiten auf einmal prüfen*.
Wir wenden den Spektroskopie-Ansatz in kleinen Fallbeispielen aus Verifikation und Übersetzung nebenläufiger Programme an.
Zentrale Teile der Arbeit werden durch eine *Isabelle/HOL-Formalisierung* gestützt.
:::

::::{.content-visible when-format="pdf"}

## Summary {.unnumbered .unlisted}

{{< contents summary-block-en >}}

\newpage
\thispagestyle{empty}

## Zusammenfassung {.unnumbered .unlisted}

{{< contents summary-block-de >}}

::::

\newpage
\thispagestyle{empty}

:::{.content-visible when-format="html"}
:::: {.panel-tabset}

## Summary

{{< contents summary-block-en >}}

## Zusammenfassung

{{< contents summary-block-de >}}

::::

---

<div style="text-align: center; font-size:2em;"><a href="https://generalized-equivalence-checking.equiv.io/Generalized-Equivalence-Checking-of-Concurrent-Programs.pdf"><i class="bi bi-file-pdf"></i> View PDF </a></div>

---

### Thesis Defense 2025-07-28

Join my **thesis defense** on **2025-07-28**, 10:30–12:00, in room BEL 301 ([Villa Bell @ TU Berlin](https://www.ec2-big-nse.de/directions-1/directions-to-villa-bell)).
Afterwards, there will be lunch and more talks. (Details will follow.)

----

### Dedication {.unnumbered .unlisted}
:::

\par\vspace*{4cm}

> To the memory of **Mark** Alexander **Sibly**,
> 
> `\raggedleft`{=latex}
> creator of the programming language in which I wrote my first concurrent program, and a profound influence on me `\\`{=latex} and so many others!

\vfill
\par

\newpage
\thispagestyle{empty}

### Acknowledgments {.unnumbered .unlisted}

This research project started due to Covid, in a way.
Because of the pandemic, CONCUR'20 was taking place as an online event.
And one afternoon, after listening to the talks, sitting alone in my office, I started to [implement a small idea](https://github.com/benkeks/equivalence-fiddle/commit/f188bc9a1ca18d4c27054bfbb8d652322b57f58f) on generalizing the bisimulation game.
Last year, the office was closed---together with the whole building---because of rusty pipes.
Unfortunately, that's not the only thing that's been going wrong, since.
Crazy times!

That this research project has still reached the stage of a PhD thesis, is thanks to many great people (sorted by category, mostly in order of appearance).

- **Environment:**
  Uwe Nestmann and my colleagues at the Modelle und Theorie Verteilter Systeme group, especially my lovely office mates Edgar Arndt and Valeria Zahoransky.
  Alex Wiemhoefer, who offered a desk in her office when mine was closed.
  My “Sunday friends” and my parents.
  You're all amazing!
- **Hospitality:**
  The organizers of the VTSA Summer School 2021 in Liège.
  Rob van Glabbeek and the Laboratory for Foundations of Computer Science for my 2023 stay in Edinburgh.
  Julia (and Fréd and kids) as well as Rosi for hosting me during visits in Paris and Oldenburg.
  David N. Jansen together with Lijun Zhang's group at the Institute of Software, Chinese Academy of Sciences for my 2024 stay in Beijing.
- **Collaboration:**
  David N. Jansen, who discovered and corrected crucial flaws in my ideas. 
  Caroline Lemke, who found out why “my” energy games are indeed decidable. 
  And many more marvelous students and collaborators (listed in @sec-artifacts-papers).
- **Co-writing:** Schrippe, Baum, Alina, and Anna S0phia.
- **Feedback** on parts of this thesis:
  Nadine Karsten,
  Caroline Lemke,
  Andrei Aleksandrov,
  Dominik Geißler,
  Uli Fahrenberg,
  Karl Mattes,
  Jeroen Keiren,
  Uwe Nestmann,
  Amelie Heindl,
  Gabriel Vogel,
  Sebastian Wolf,
  David Karcher,
  David N. Jansen.

```{=latex}
{
\newpage
\hypersetup{linkcolor=black}
\setstretch{1.0}
\tableofcontents
\setstretch{1.1}
}
\mainmatterforreal

\newcommand{\partfigure}{\partfigureone}
\newcommand{\partfigureone}{
  \begin{adjustbox}{max width=.8\textwidth, center}
    \begin{tikzpicture}[rounded corners = 5, outer sep=1mm]
    \tikzstyle{every node}=[font=\normalsize, align=center]
      \draw[thick, gray, fill=gray] (-.5,-.7) rectangle (12.5,-.3);
      \draw[thick, fill=white] (0,1.5) rectangle (12,-0.5);
      \node at (6,-0.25) {\textbf{Preliminaries} \quad Chapter \ref{sec-preliminaries}};
      \draw  (0.1,1.4) rectangle  node {Behavior \& equivalences} (3.95,0.1);
      \draw  (4.05,1.4) rectangle  node {Modal logics}
      (7.95,0.1);
      \draw  (8.05,1.4) rectangle  node {Games \vphantom{q}} (11.9,0.1);

      \draw[thick]  (1,3) rectangle  node {\textbf{Strong spectrum} \\ \textbf{\& spectroscopy problem} \\ Chapter~\ref{sec-spectrum}} (8,1.5);
      %\draw[thick] (8,1.5) -- (8,3) -- (6,3) -- (6,4.5) -- (12,4.5) -- (12,1.5) -- cycle;
      % \node at (9,3.75) {\textbf{Approach: Equivalence} \\ \textbf{problems as energy games} \\ Chapter \ref{sec-approach}};
      %\draw (8.1,2.9) rectangle node {Energy games} (11.9,1.6);

      %\draw[thick] (2,3) -- (2,6) -- (12,6) -- (12,4.5) -- (6,4.5) -- (6,3) -- cycle;
      %\node at (4,4.5) {\textbf{Spectroscopy of} \\ \textbf{the strong spectrum} \\ Chapter \ref{sec-strong-spectroscopy}};
      %\draw (8.1,5.9) rectangle node {Individual checkers} (11.9,4.6);

      %\draw[thick] (0,1.5) -- (0,6) -- (2,6) -- (2,3) -- (1,3) -- (1,1.5) -- cycle;
      %\node at (1,4.5) {\textbf{Weak} \\ \textbf{spectrum} \\ Chapter \ref{sec-weak-spectrum}};

      %\draw[thick] (0,7.5) rectangle node {\textbf{Weak spectroscopy} \\ Chapter \ref{sec-weak-spectroscopy}} (12,6);
    \end{tikzpicture}
  \end{adjustbox}
  \renewcommand{\partfigure}{\partfiguretwo}
}
\newcommand{\partfiguretwo}{
  \begin{adjustbox}{max width=.8\textwidth, center}
    \begin{tikzpicture}[rounded corners = 5, outer sep=1mm]
    \tikzstyle{every node}=[font=\normalsize, align=center]
      \draw[thick, gray, fill=gray] (-.5,-.7) rectangle (12.5,-.3);
      \draw[thick, gray, fill=white] (0,1.5) rectangle (12,-0.5);
      \node[gray] at (6,-0.25) {\textbf{Preliminaries} \quad Chapter \ref*{sec-preliminaries}};
      \draw[gray]  (0.1,1.4) rectangle  node {Behavior \& equivalences} (3.95,0.1);
      \draw[gray]  (4.05,1.4) rectangle  node {Modal logics}
      (7.95,0.1);
      \draw[gray]  (8.05,1.4) rectangle  node {Games \vphantom{q}} (11.9,0.1);

      \draw[gray, thick]  (1,3) rectangle  node {\textbf{Strong spectrum} \\ \textbf{\& spectroscopy problem} \\ Chapter~\ref*{sec-spectrum}} (8,1.5);
      
      \draw[thick] (8,1.5) -- (8,3) -- (6,3) -- (6,4.5) -- (12,4.5) -- (12,1.5) -- cycle;
      \node at (9,3.75) {\textbf{Approach: Equivalence} \\ \textbf{problems as energy games} \\ Chapter \ref{sec-approach}};
      \draw (8.1,2.9) rectangle node {Energy games} (11.9,1.6);

      \draw[thick] (2,3) -- (2,6) -- (12,6) -- (12,4.5) -- (6,4.5) -- (6,3) -- cycle;
      \node at (4,4.5) {\textbf{Spectroscopy of} \\ \textbf{the strong spectrum} \\ Chapter \ref{sec-strong-spectroscopy}};
      \draw (8.1,5.9) rectangle node {Individual checkers} (11.9,4.6);

      %\draw[thick] (0,1.5) -- (0,6) -- (2,6) -- (2,3) -- (1,3) -- (1,1.5) -- cycle;
      %\node at (1,4.5) {\textbf{Weak} \\ \textbf{spectrum} \\ Chapter \ref{sec-weak-spectrum}};

      %\draw[thick] (0,7.5) rectangle node {\textbf{Weak spectroscopy} \\ Chapter \ref{sec-weak-spectroscopy}} (12,6);
    \end{tikzpicture}
  \end{adjustbox}
  \renewcommand{\partfigure}{\partfigurethree}
}
\newcommand{\partfigurethree}{
  \begin{adjustbox}{max width=.8\textwidth, center}
    \begin{tikzpicture}[rounded corners = 5, outer sep=1mm]
    \tikzstyle{every node}=[font=\normalsize, align=center]
      \draw[thick, gray, fill=gray] (-.5,-.7) rectangle (12.5,-.3); 
      \draw[thick, gray, fill=white] (0,1.5) rectangle (12,-0.5);
      \node[gray] at (6,-0.25) {\textbf{Preliminaries} \quad Chapter \ref*{sec-preliminaries}};
      \draw[gray]  (0.1,1.4) rectangle  node {Behavior \& equivalences} (3.95,0.1);
      \draw[gray]  (4.05,1.4) rectangle  node {Modal logics}
      (7.95,0.1);
      \draw[gray]  (8.05,1.4) rectangle  node {Games \vphantom{q}} (11.9,0.1);

      \draw[gray, thick]  (1,3) rectangle  node {\textbf{Strong spectrum} \\ \textbf{\& spectroscopy problem} \\ Chapter~\ref*{sec-spectrum}} (8,1.5);
      
      \draw[gray, thick] (8,1.5) -- (8,3) -- (6,3) -- (6,4.5) -- (12,4.5) -- (12,1.5) -- cycle;
      \node[gray] at (9,3.75) {\textbf{Approach: Equivalence} \\ \textbf{problems as energy games} \\ Chapter \ref*{sec-approach}};
      \draw[gray] (8.1,2.9) rectangle node {Energy games} (11.9,1.6);

      \draw[gray, thick] (2,3) -- (2,6) -- (12,6) -- (12,4.5) -- (6,4.5) -- (6,3) -- cycle;
      \node[gray] at (4,4.5) {\textbf{Spectroscopy of} \\ \textbf{the strong spectrum} \\ Chapter \ref*{sec-strong-spectroscopy}};
      \draw[gray] (8.1,5.9) rectangle node {Individual checkers} (11.9,4.6);

      \draw[thick] (0,1.5) -- (0,6) -- (2,6) -- (2,3) -- (1,3) -- (1,1.5) -- cycle;
      \node at (1,4.5) {\textbf{Weak} \\ \textbf{spectrum} \\ Chapter \ref{sec-weak-spectrum}};

      \draw[thick] (0,7.5) rectangle node {\textbf{Weak spectroscopy} \\ Chapter \ref{sec-weak-spectroscopy}} (12,6);
    \end{tikzpicture}
  \end{adjustbox}
  \renewcommand{\partfigure}{}
}

\makeatletter
\pretocmd{\@endpart}{\vfil\partfigure}{}{}
\makeatother
```

