name: Build with Quarto and deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt install pdf2svg

      - name: Install TeXlive
        uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: |
            scheme-basic
            collection-xetex
            xcolor
            standalone
            amsmath
            amsthm
            amsfonts
            stmaryrd
            mathpartir
            booktabs
            fontawesome5
            fontspec
            unicode-math
            newunicodechar
            setspace

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # To install LaTeX to build PDF book 
          tinytex: false
          # version: SPECIFIC-QUARTO-VERSION-HERE
       # add software dependencies here and any libraries 
         # From https://github.com/actions/setup-python
         # - name: Setup Python
         #   uses: actions/setup-python@v3

      - name: Render with Quarto 
        uses: quarto-dev/quarto-actions/render@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _book/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
